name: API Automation Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      run: |
        pytest src/tests/test_suite_01_basic.py -v --tb=short
    
    - name: Run CRUD tests
      run: |
        pytest src/tests/test_suite_02_crud.py -v --tb=short
    
    - name: Run E2E tests
      run: |
        pytest src/tests/test_suite_03_e2e.py -v --tb=short
    
    - name: Generate test report
      run: |
        pytest --junitxml=test-results/junit.xml
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: test-results